### ISSUE TITLE
Solve the password mask problem

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#103]
According to doc by airflow, they masks sensitive info like password, the problem is we don't know how to use the password in dag, seems we can not unmask them?

https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/index.html
https://airflow.apache.org/docs/apache-airflow/stable/concepts/variables.html
https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/mask-sensitive-values.html

Please let me know if you want to make a try and need more necessary info.

**Comment by huang-pan** [comment]
Please see the work in https://github.com/Greenstand/treetracker-airflow-dags/issues/156

**Comment by huang-pan** [comment]
Passwords and keys are automatically masked in the Airflow Variables UI https://dev-k8s.treetracker.org/airflow/variable/list/ and logs. Please see:

https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/security/secrets/mask-sensitive-values.html

![Screen Shot 2023-02-06 at 1 19 00 PM (2)](https://user-images.githubusercontent.com/10567714/217090363-dfdef40a-7d5c-4f4d-bdaa-9b0875a03458.png)

**Comment by huang-pan** [comment]
Airflow Variables are not masked when they are actually used in the code. This has been tested and verified. Please see:

![Screen Shot 2023-02-06 at 1 16 52 PM (2)](https://user-images.githubusercontent.com/10567714/217090558-478f8797-27dd-4a35-ae13-48bb2b878154.png)

![Screen Shot 2023-02-06 at 1 16 17 PM (2)](https://user-images.githubusercontent.com/10567714/217090619-c8842b89-f0a3-43d0-88dd-9cdfb796e8f2.png)


<img width="1440" alt="Screen Shot 2023-02-06 at 1 16 17 PM" src="https://user-images.githubusercontent.com/10567714/217090736-0eb04011-1555-4b3a-98f7-6ae20bba7825.png">

**Comment by huang-pan** [comment]
You can go ahead and close this issue. The above code will be applied to issue https://github.com/Greenstand/treetracker-airflow-dags/issues/156

**Comment by dadiorchen** [comment]
@huang-pan this is not a normal case for the variable of password, it is the URL connection put in the variable, so the airflow can not do the mask, if you check here:

https://dev-k8s.treetracker.org/airflow/variable/list/

The variable: DATABASE_URL is something like: 	postgresql://doadmin:xxxxxxxxxxxxx@db-postgresql-sfo2-nextgen-do-user-1067699-0.db.ondigitalocean.com:25060/treetracker?sslmode=no-verify

so the password for the database is exposed to everyone.

The reason that why we have to use a explicit database connection string is here:

https://github.com/Greenstand/treetracker-airflow-dags/blob/813d21011e567b3c7b03daaaf79bc9e3d2ca08bb/migrate_stakeholders_dag.py#L56-L59

Here I have to set the whole connection string as the env string, because if I use the DB_PASSWORD as variable, then I will get masked stars in the env, I guess this is because the airflow recognized this password and did the mask when output, right?
If we can find a way to use the password direct as a env variable for the docker image, that would be perfect?

**Comment by huang-pan** [comment]
Did you not see my thorough explanation in https://github.com/Greenstand/treetracker-airflow-dags/issues/156 and https://github.com/Greenstand/treetracker-airflow-dags/issues/103?

The password is only masked in the Airflow UI and logs. It's not masked when you pass the variable to the function that's using it. I know this for a fact because we use this method at Roofstock and it works.
