### ISSUE TITLE
The country leader board by continent is wrong

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#120]
The response of this url:
https://prod-k8s.treetracker.org/query/countries/leaderboard/North%20America

is the result of this dag/sql:

https://github.com/Greenstand/treetracker-airflow-dags/blob/4c9f68e674a8a8d8dd7e00151e475e44fe82456b/lib/country_leader_board.py#L41-L56

It's wrong, there are duplicated record for United States, please help to find the problem with this SQL

**Comment by dadiorchen** [comment]
@Mohmn what do you think?

**Comment by Mohmn** [comment]
couldn't properly debug the query because it runs fine on the test db env @dadiorchen

**Comment by Mohmn** [comment]
my guess would be that u r using distinct for the count ('count(distinct(tree_id)) ') only, i think u need to add disticnt on tree_id's itself then count them seperately @dadiorchen

**Comment by dadiorchen** [comment]
yea...back to the problem, how do I board you on the prod...

**Comment by dadiorchen** [comment]
Has been solved
