### ISSUE TITLE
Run command from a docker image

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#121]
Sometimes we need to run some program in another language, say, node.js, for example, we need to run scripts written in this repo: https://github.com/Greenstand/domain-migration-scripts, so the idea is: create a docker image from the repo, and run it on airflow.

**Comment by hcars** [comment]
Hey, @dadiorchen, I'm interested in this issue. So, let me get this straight, I need to:

1. Create a docker image with airflow installed and all the requisite environment for domain-migration-scripts
2. Run the scripts from the domain-migration-scripts from the airflow panel executing in a container built from the image in 1.

**Comment by dadiorchen** [comment]
@hcars that's fantastic! I will support you as much as I can.

I think as the first step, we can make the question domain small: just run any simplest docker container on airflow, this is good enough for this issue, then we will try to introduce the domain migration container into airflow. Because for the domain-script repo, we need extra work to build the docker image for it, we have done some similar work in other repo, like this: https://github.com/Greenstand/treetracker-reporting this repo will be deployed to docker hub everytime when we got new version: https://registry.hub.docker.com/r/greenstand/treetracker-reporting
What do you think?

**Comment by dadiorchen** [comment]
By the way, what's your name on our slack community? @hcars
