### ISSUE TITLE
Need a more secure way to set the db credential env

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#156]
In this dag we use variables on airflow to set the db connection: https://github.com/Greenstand/treetracker-airflow-dags/blob/b9be27f21515f49e13cdb41d3206f476c72758a2/domain_migration_dag.py#L55-L58

The downside of this is that we need to explicitly set the db connection string in the airflow dashboard, it is unsafe, we need to use a better way to provision the db settings to the k8s pod, configmap or secret from k8s is good but we need to find the way to set it and prove it in the dev en.

**Comment by huang-pan** [comment]
We can leverage the work on https://github.com/Greenstand/treetracker-airflow-dags/issues/92 to resolve this issue.

**Comment by huang-pan** [comment]
Please see issue https://github.com/Greenstand/treetracker-airflow-dags/issues/103 for an explanation of how password masking works in Airflow.

**Comment by huang-pan** [comment]
Password masking has been tested working successfully on my local Airflow:

Password masked in Airflow Variables UI. Password still exportable to a JSON file, but only the admin user can see the Airflow Variables in the UI.
![Screen Shot 2023-02-06 at 1 19 00 PM (2)](https://user-images.githubusercontent.com/10567714/217092575-6c7ce19c-48a4-4050-bc86-0ec1816c2098.png)

Test code / DAG:
![Screen Shot 2023-02-06 at 1 16 52 PM (2)](https://user-images.githubusercontent.com/10567714/217092704-425a5d1a-c620-4d85-97d1-7d64dc3a2ced.png)

Passwords masked in Airflow logs:
![Screen Shot 2023-02-06 at 1 16 17 PM (2)](https://user-images.githubusercontent.com/10567714/217092819-333d2448-dd62-49c2-9346-2e4382c9ac06.png)

Passwords not masked in actual use:
<img width="1440" alt="Screen Shot 2023-02-06 at 1 16 17 PM" src="https://user-images.githubusercontent.com/10567714/217092880-ae88751d-4a3e-4468-bc6e-825b78845ea9.png">

**Comment by huang-pan** [comment]
A masked password for DATABASE_URL has been added to https://dev-k8s.treetracker.org/airflow/variable/list/

![Screen Shot 2023-02-06 at 1 36 22 PM (2)](https://user-images.githubusercontent.com/10567714/217093380-1e6d2884-182e-4f64-b3af-168b30fbba38.png)

Similar Variables need to be added to prod Airflow. Only the admin user can access Airflow Variables from the UI.

I'll create a Pull Request now for the updated code.
