### ISSUE TITLE
Update Airflow development instructions

### ISSUE THREAD

**Issue by huang-pan** [Greenstand/treetracker-airflow-dags#182]
I'm a volunteer currently developing on Greenstand's Airflow. I'll update the instructions for getting the Airflow environment set up so that you can start developing on it. It seems that Greenstand has more volunteers who are interested in helping out with Airflow.

**Comment by huang-pan** [comment]
Can you approve the PR @dadiorchen

**Comment by dadiorchen** [comment]
@huang-pan definitely, thank you!

**Comment by huang-pan** [comment]
Thanks!
