### ISSUE TITLE
Check out the problem with this PR

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#188]
This PR https://github.com/Greenstand/treetracker-airflow-dags/pull/187 is to solve the leaderboard problem, but the result of the PR is wrong, no data get inserted into the target table, we need to find out the problem and solve it.

It might be because of the return column of the big SQL is wrong.

**Comment by huang-pan** [comment]
I'll take a look at it.

**Comment by dadiorchen** [comment]
@huang-pan thank you! I thought this is a tiny problem, you have finished the major part, so I tag it with goog first issue

**Comment by huang-pan** [comment]
This PR https://github.com/Greenstand/treetracker-airflow-dags/pull/190 fixes this issue.

I forgot to check the column order and type returned from the SQL query. The below works:

    select cast(top_countries_cte.planted as bigint), region_cte.id region_id, top_countries_cte.name, region_cte.centroid

<img width="1440" alt="Screen Shot 2023-02-23 at 6 21 55 PM" src="https://user-images.githubusercontent.com/10567714/221079368-cb7a5706-13b0-44b4-98aa-36e4b8b164c2.png">

<img width="1440" alt="Screen Shot 2023-02-23 at 6 21 59 PM" src="https://user-images.githubusercontent.com/10567714/221079404-eaf047fb-8af4-4289-96e3-acb973a84f86.png">

![Screen Shot 2023-02-23 at 6 34 55 PM (2)](https://user-images.githubusercontent.com/10567714/221079441-76be3fcd-c1b5-43c1-bfae-f97e39d67805.png)
