### ISSUE TITLE
Refine the date calculation

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#21]
https://github.com/Greenstand/treetracker-airflow-dags/blob/b656517f6564acef8d4fc41f0d5a6316fb8d9ef8/lib/capture_export.py#L8-L17

The end date of the month is inaccurate, not every month is 31 days, so need to correct it.

Also, we can create a function in the util.py to do so, and use unit test to cover it.

**Comment by dark-teal-coder** [comment]
Hi, I've written the code for this: https://gist.github.com/dark-teal-coder/3308cf5b0a6d4927f37d2f416446b414

I don't know how to update that part in your program so I've saved it as a public gist. You can copy it and add it to your script.

**Comment by sixlim** [comment]
Hi @dadiorchen, is this still open ?

**Comment by dadiorchen** [comment]
@sixlim yes, this is open, I have assianged to you

**Comment by sixlim** [comment]
@dadiorchen , I get the latest code, the code had changed since then, and now the argument `date` for function `capture_export`  is now in 'YYYY-mm-dd' format, with value generated from `datetime.now().strftime("%Y-%m-%d")`, which will be valid. 

So it seems the previous issue described above does not exist anymore. Do you mind describe if any new requirement for this? 
Thanks !

**Comment by dadiorchen** [comment]
@sixlim yes, we changed a little bit on the code, which doesn't mean we no longer need the last-date-of-month calculation, but yes, let's close this issue for the time being.

@sixlim do you want to join our community so you can find more stuff and people over there?

**Comment by sixlim** [comment]
> @sixlim yes, we changed a little bit on the code, which doesn't mean we no longer need the last-date-of-month calculation, but yes, let's close this issue for the time being.
> 
> @sixlim do you want to join our community so you can find more stuff and people over there?

@dadiorchen sure, I will be glad if anything I can help out with.

**Comment by dadiorchen** [comment]
@sixlim great, please leave your email so I can invite you
