### ISSUE TITLE
Cut the csv to smaller files.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#34]
https://github.com/Greenstand/treetracker-airflow-dags/blob/main/lib/capture_export.py

For this script, we are now dumping all data to single file, we need to detect the size of csv file and split to smaller ones, and name the file with pattern like:  [original_file_name]-part1/part2/....csv

**Comment by DerMoehre** [comment]
@dadiorchen is this issue still available?

**Comment by dadiorchen** [comment]
@DerMoehre definitely! please help us on this!

**Comment by DerMoehre** [comment]
@dadiorchen okay. I will try to make an improvement :)

**Comment by dadiorchen** [comment]
TDD is my answer, @DerMoehre we are using unit test tool for python in this project, as described in the readme, so please test it in unit test, with some mock data/function if needed.

**Comment by DerMoehre** [comment]
My idea is, to count the rows of the file with something like

`row_count = sum(1 for row in csv.reader(f))`

and after that, to divide the rows in several packages eg. 5 files. 

I have to get a bit more familiar with airflow and the overall structure :)

**Comment by dadiorchen** [comment]
@DerMoehre it is possible to develop without airflow, (there are some doc in readme), but it is welcome to learn and use it  :D

**Comment by wesleycheung0** [comment]
@dadiorchen  Is this issue still valid?

**Comment by dadiorchen** [comment]
@wesleycheung0 yes!

**Comment by wesleycheung0** [comment]
Sounds good. I’m taking a look at it. On Feb 22, 2023, at 10:35 PM, Dadiorchen ***@***.***> wrote:﻿
@wesleycheung0 yes!
