### ISSUE TITLE
Report failing airflow jobs into the production-vertical channel

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-airflow-dags#85]
There are 2 options
(1) A slack integration job
(2) Using a custom slack email address that directs to a channel 

(2) is already set up for the reporting API, but there are 2 problems
         * The SMTP connection is not working correctly so the email is not sent
         * This is set up to trigger for all environments, but we'd only want reporting to the production-vertical channel in production

What we want:
1. When any airflow job fails in production, send a message with details into #production-vertical
2. When any airflow job fails in any other environment, do NOT send a message into slack

For option (1) some details here: https://www.reply.com/data-reply/en/content/integrating-slack-alerts-in-airflow, which could possibly be used via: 'on_failure_callback': some_function ?

**Comment by huang-pan** [comment]
This issue overlaps with this: https://github.com/Greenstand/treetracker-airflow-dags/issues/135
and can be resolved after 135 is complete.
