### ISSUE TITLE
Set up the user permission for operators.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#92]
Basically, this is about setting up the airflow's user system, to be able to assign specific permission to some users/accounts.

Currently, we need a role, by assigning the role to a user, then the user can do: 
* View/monitor the 'assign_tree_to_cluster' task
* Manually run it.

Note, we can now use airflow's dashboard to set up this permission, but it's a temporary solution, everytime we deploy this repo to prod, the permission will get erased, this is because that we chose github repo as the source of the user system, so we need to set it (the role, permission, user) in the repository of airflow, say, this repo.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/171076946-2cde26ab-02c9-4bf7-9d71-2124e782133f.png">

**Comment by huang-pan** [comment]
For this one this file needs to be modified: https://github.com/Greenstand/treetracker-infrastructure/blob/master/airflow/roles/airflow/tasks/main.yml to add different types of users according to https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/airflow-users.md

In general, please see https://github.com/airflow-helm/charts/tree/main/charts/airflow on how to configure the Airflow installation on Kubernetes using Ansible and Helm.

**Comment by huang-pan** [comment]
Airflow is installed on the Kubernetes clusters through a Helm chart and using ansible:

https://github.com/Greenstand/treetracker-infrastructure/tree/master/airflow

The 'ansible-playbook airflow-playbook.yml -i environments/development' command installs a specially configured Helm chart with this additional configuration: 

https://github.com/Greenstand/treetracker-infrastructure/blob/master/airflow/roles/airflow/tasks/main.yml

It's simply a matter of adding new users to the above file:

<img width="1440" alt="Screen Shot 2023-02-02 at 2 50 43 PM" src="https://user-images.githubusercontent.com/10567714/216469106-3bc9c956-dbf3-4645-885c-a46ee1ac346e.png">

Please see: https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/airflow-users.md

I added these users:
- viewer: can only view DAGs
- user: can view and rerun DAGs

Please see this document for information about Airflow roles:

https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/security/access-control.html

**Comment by huang-pan** [comment]
We can change the passwords and emails for 'user' and 'viewer' if needed.

**Comment by dadiorchen** [comment]
@huang-pan may I ask how do we generate the password? there is a {{password}} in the file, but I don't know how do we handle it?

**Comment by huang-pan** [comment]
I updated the https://github.com/Greenstand/treetracker-infrastructure/blob/master/airflow/roles/airflow/tasks/main.yml file to take passwords for the Airflow users: user, viewer from the Airflow namespace in Kubernetes. The Secrets (passwords) airflow-user-credentials and airflow-viewer-credentials have been set in the dev k8s deployment Airflow namespace. I also shared the Airflow user and viewer passwords with you in LastPass.

USER_PASSWORD: airflow-user-credentials (set in dev k8s deployment Airflow namespace Secrets)
VIEWER_PASSWORD: airflow-viewer-credentials (set in dev k8s deployment Airflow namespace Secrets)

The user, viewer logins with the new passwords have been tested and working in https://dev-k8s.treetracker.org/airflow/login/

![Screen Shot 2023-02-03 at 5 06 10 PM (2)](https://user-images.githubusercontent.com/10567714/216737025-81efeb5a-8cac-4e2c-93f1-c0c27a133070.png)

**Comment by huang-pan** [comment]
Similar Secrets have to be set in the prod Kubernetes cluster Airflow namespace. Here are the instructions for setting them from the UI:

- Select Airflow Namespace, go to Secrets, click the + button in the upper right

![Screen Shot 2023-02-03 at 5 13 18 PM (2)](https://user-images.githubusercontent.com/10567714/216737422-12c93998-6c81-4f5b-8604-bd37431deaef.png)

- paste this YAML:
kind: Secret
apiVersion: v1
metadata:
  name: airflow-user-credentials
  namespace: airflow
data:
  password: mypassword
type: Opaque

![Screen Shot 2023-02-03 at 5 14 46 PM (2)](https://user-images.githubusercontent.com/10567714/216737540-9c740995-4650-44d2-a6d4-2f73d1068fde.png)

**Comment by dadiorchen** [comment]
Thank you! @huang-pan this turns out to be a good guidebook for us :)

**Comment by huang-pan** [comment]
Thanks, can you approve the PR?

**Comment by huang-pan** [comment]
Instead of using the k8s UI to add secrets, will add sealed secrets airflow_user_sealed_password, airflow_viewer_sealed_password to:

https://github.com/Greenstand/treetracker-infrastructure/blob/master/airflow/environments/development/group_vars/local
https://github.com/Greenstand/treetracker-infrastructure/blob/master/airflow/environments/production/group_vars/local
https://github.com/Greenstand/treetracker-infrastructure/blob/master/airflow/environments/test/group_vars/local

please see:

https://github.com/Greenstand/treetracker-infrastructure/tree/3c01bb9c06351b6478bcca314dd5b8aa97bdd645/sealed-secrets

**Comment by dadiorchen** [comment]
@huang-pan maybe you can go first and do it for the dev? Then I can copy your steps and change things necessary for prod?

**Comment by huang-pan** [comment]
I went and followed the instructions in: 

https://github.com/Greenstand/treetracker-infrastructure/tree/3c01bb9c06351b6478bcca314dd5b8aa97bdd645/sealed-secrets

kubectl config set-context --current --namespace=airflow
kubectl get sealedsecrets
create airflow-user-credentials.yaml:
kind: Secret
apiVersion: v1
metadata:
  name: airflow-user-credentials
  namespace: airflow
data:
  password: <mypassword>
type: Opaque

**Comment by huang-pan** [comment]
PR https://github.com/Greenstand/treetracker-infrastructure/pull/141 updated with sealedsecret passwords for airflow-user-credentials and airflow-viewer-credentials

**Comment by huang-pan** [comment]
Approve the PR, check out the latest code from the git repo, then deploy to the prod kubernetes cluster:

- cd ~/Greenstand/git/treetracker-infrastructure/airflow
- ansible-playbook airflow-playbook.yml -i environments/production

You should now be able to log into https://prod-k8s.treetracker.org/airflow/home using the user and viewer logins.

The user and viewer passwords have been shared with @dadiorchen in LastPass.

**Comment by dadiorchen** [comment]
@huang-pan thank you! I will go forward to do the release

**Comment by huang-pan** [comment]
Updated PR https://github.com/Greenstand/treetracker-infrastructure/pull/141/files with updated instructions on how to install and configure Airflow on Kubernetes in airflow/README.md
